language: php

php:
  - 7.0
  - 7.1

env:
  - TRAVIS_ENV=1

before_script:
  - composer install --dev

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_success:
  - '[ "$TRAVIS_PHP_VERSION" != "hhvm" ] && vendor/bin/coveralls -v'